---
apiVersion: v1
kind: Secret
metadata:
  name: anurag-saran-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-gh/anurag-saran-gateway-gitops
